version: '3.8'

services:

  # Database Configuration
  postgres:
    image: postgres:15
    container_name: conecta_irece_api_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: conecta_irece_api_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # API configuration
  api:
    build: .
    container_name: conecta_irece_api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/conecta_irece_api_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: